project:
  type: website
  output-dir: docs

website:
  title: "{{< fa solid chart-simple size=large >}} ethics 4 data science"
  navbar:
    lowercase: true
    right:
    - text: "references"
      menu:
      - text: "Bit by Bit"
        href: https://www.bitbybitbook.com/en/1st-ed/ethics/
      - text: "Fairness and Machine Learning"
        href: https://fairmlbook.org/
      - text: "Data Feminism"
        href: https://data-feminism.mitpress.mit.edu/
      - text: "RSS Guidelines"
        href: https://rss.org.uk/RSS/media/News-and-publications/Publications/Reports%20and%20guides/A-Guide-for-Ethical-Data-Science-Final-Oct-2019.pdf
      - text: "ASA Guidelines"
        href: https://www.amstat.org/your-career/ethical-guidelines-for-statistical-practice
      - text: "ACM Guidelines"
        href: https://www.acm.org/code-of-ethics
    - text: "{{< fa solid house size=large >}} content"
      file: index.qmd
    - text: "{{< fa solid user size=large >}} about"
      file: about.qmd
  site-url: http://ethics4ds.com
  
format:
  html:
    cookie_consent:
      style: simple
      type: express
      palette: light
      lang: en
      cookies_policy: url
    citations: false
    theme: cosmo
    css: styles.css
    toc: true
    
collections:
  research:
    share: [twitter, linkedin]
    categories: false
  teaching:
    share: [twitter, linkedin]
    categories: false
  creative_commons: CC BY

editor: source
execute: 
  freeze: auto


